### PR TITLE
[3.6] Transparent lockscreen on mediaplayer fullscreen videos/pictures showing

### PR DESCRIPTION
**Pull request by hackoon**
fullscreen media-players and slide-shows continue showing when lockscreen is activated
It's very small and affects only stage.py and adds util/mplayer.py.
Works only one single monitor yet, please test or give me feedback on how to set opacity for different monitors. Would also be nice to add an extra option in cinnamon-settings.

Features:

.    no wallpaper image
.    no widgets - only on the active unlock screen
.    100% transparency for the screensaver window
.    checks if player is focused and has fullscreen dimensions
.    changes transparency to 0% if player closes and puts widgets and wallpaper back
.    changes position of unlock and clock widget
.    works with a range of players / slideshows
.    only activates when settings -> media control is enabled

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @hackoon,

Sorry it took so long to review your PR. It scared me a bit and it was seducing as well... so I had to think about it for a while.

@mtwebster I wouldn't mind your opinion on this as well.

First, you need to add mplayer.py to src/util/Makefile.am, otherwise it's missing post-compilation.
I couldn't test it properly... it wouldn't activate for me, maybe I lose focus when pressing CTRL+L, or maybe it's because I've got 2 monitors.. either way, it doesn't really matter... I've a problem with a the feature itself, not the implementation.

Although I like the idea... I've two problems with it.

1. The use case you're trying to solve should be solved (and is solved largely in many cases) by the media-player. VLC, xplayer and many other players inhibit the session when playing media. In other words, the screensaver doesn't lock when a movie is playing.

2. I'm really worried about having a transparent screensaver... because it's like a can of worms, it opens to many use cases which we need to predict and take into account... and I wouldn't know where to begin... For instance, say MPV is playing a movie, the screensaver locks in transparent mode... the movie ends and MPV closes... and the screensaver is now showing my desktop.. and my opened files. That's not good. Say I get an email during playback... everybody can see the notification.. not good.

For the few players which don't support session inhibition we provide an inhibit applet people can use.

For these reasons, I'd prefer to reject this feature and close the PR.

**Comment by hackoon** [comment]
Hello Clement

I was of the net for a few days, now I found some time to answer your email.
Let me have a reply to your issues with the mplayer addition.

First before you reject it please test it (just deactivate or mirror one of your screens)
Second, I apologize for not giving a perfect description what this does. I is not a patch for player who don't inhibit the screensaver. I dis program this of my personal experiences in a real secure environment. People often use their equipment to show others slideshows or videos. If those are long they usually get a call or some other interruption leaving their equipment open to be accessed. This is often a serious security worry in sensitive environments. A well trained hacker won't need much time if he has access to the console.
For the rest of your issues with that can of worms - when the player closes, the process will automatically change to standard screensaver mode with the background, transparency set to 100% and all other plugins showing like normal - this is already implented.
Other thing is that this will only activate if the player is fullscreen. for popups showing it is possible to find some workaroud for this - I am willing to improve this addon at your request.

Please be patient with this implementation, it needs obviously more testing and improvement.

**Comment by clefebvre** [comment]
Thanks @hackoon, I'll give it a go and reconsider for 3.6 the cycle.

**Comment by clefebvre** [comment]
You're missing a dependency on python3-xlib.

**Comment by clefebvre** [comment]
I tested it again and I'm sorry but I'll close this PR.

A couple of issues during testing:

- When typing the password in the lock screen, I'm not presented with the lock screen... MPV remains on the screen.. that's not giving me much confidence, I would not press enter in such conditions, worrying which app has focus and where my password could end up going.

- I launch MPV, double click it to set it fullscreen, press CTRL+ALT+L to lock the screen. I know it's locked because I can no longer interact with MPV with the keyboard. Until there it all looks good... but if I double-click MPV it goes to window mode. Not only can I see my DE, I can click the panel, launch apps, close apps, focus windows... etc etc.. I've got full control, I'm just missing the keyboard (which is grabbed by csr).

Whether this issue above is fixable or not, I'm not confident with this PR. By design I really don't like the idea.

**Pull request closed without merging**
