### PR TITLE
Cleanup autotools

### PR DESCRIPTION
**Pull request by eli-schwartz**
In order to make progress on #310 and its meson 0.45 requirement, I cannot use `rename arg in install_data` (which was introduced in 0.46). In order to do this properly, I'd need to use proper filenames and install_subdir, which as a bonus makes this a lot nicer for both autotools and meson. But it does mean I cannot just have meson be a drop-in replacement for autotools -- I need to adapt the project layout itself too.

Submitted separately because I want to get master into a less snarled state to make a clean meson port.

### CODE REVIEW

**Comment by Fantu** [comment]
The build fails with this strange error:

> 
> The following files contain translations and are currently not in use. Please
> consider adding these to the POTFILES.in file, located in the po/ directory.
> 
> libcscreensaver/cs-auth-pam.c
> src/pamhelper/cinnamon-screensaver-pam-helper.c
> src/passwordEntry.py
> src/widgets/powerWidget.py
> 
> If some of these files are left out on purpose then please add them to
> POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
> of left out files has been written in the current directory.

Can your change influence these files? From a fast look I not understand how it is possible

**Comment by Fantu** [comment]
I did another fast check, the po checker ir right, these files are missed, I suppose that before your changes didn't arrive to it even if without error, try to add these in po/POTFILES.in:
libcscreensaver/cs-auth-pam.c
src/pamhelper/cinnamon-screensaver-pam-helper.c
src/passwordEntry.py
src/widgets/powerWidget.py

After will see if there are other thing "unlocked" by your changes.

**Comment by eli-schwartz** [comment]
It's a very weird error, because it seems to be coming from `make check` which I've never run as there is no actual testsuite. But it seems to be linting the localization.... Is debian running the testsuite, even if the target is defined without really doing anything?

At any rate, I can reproduce the error by running:
```
git clone https://github.com/linuxmint/cinnamon-screensaver /tmp/test-cs-check
cd /tmp/test-cs-check
autoreconf -fi && ./configure --prefix=/usr && make && make check
```

which "successfully" fails as well. If this error occurs in CI, I don't understand how any other commits on master were ever succeeding.

**Comment by eli-schwartz** [comment]
For that matter, even if they were added, the check target would still fail with this:

```
Making check in files
make[1]: Entering directory '/tmp/test-cs-check/files'
make[1]: *** No rule to make target 'check'.  Stop.
```

It needs the fact that I've rm'ed the files/ directory, to succeed. Autotools requires a bunch of targets to be defined even if they don't do anything, in order to expose the right API -- if you add your own SUBDIRS makefiles which don't use automake, you need to define those.

**Comment by eli-schwartz** [comment]
My original PR
https://circleci.com/gh/linuxmint/cinnamon-screensaver/148
```
   dh_auto_test
	make -j36 check VERBOSE=1
```

When I replace the PR with a no-op empty commit that does nothing
https://circleci.com/gh/linuxmint/cinnamon-screensaver/151
- dh_auto_test doesn't seem to do anything.

What on earth does this mean? Why is make check running sometimes, but not always?

**Comment by eli-schwartz** [comment]
Suddenly everything works because I stopped trying to unpredictably run tests that don't exist. Yay.

**Comment by clefebvre** [comment]
I'm going to ship 4.4 without this for the following reason. It's the last version which needs to worry about 0.45.

After that we're on 0.49+.

**Comment by clefebvre** [comment]
PS: I really appreciate having files/ in there. It allows us to drop new files without worrying about impacting the build, no redundancy.

**Comment by eli-schwartz** [comment]
Oooor I could drop the middle patch and we could consider merging that.

**Comment by eli-schwartz** [comment]
Looks like CI still passes with only those two commits. :)

**Comment by eli-schwartz** [comment]
@clefebvre The only patch I really needed myself was the last patch, the others were just trying to get CI to complete. So this seems good now.

**Pull request merged**
