### PR TITLE
[WIP] rewrite in python

### PR DESCRIPTION
**Pull request by mtwebster**
See README.md for some info.

Requires git master cinnamon-desktop (commit https://github.com/linuxmint/cinnamon-desktop/commit/a4dbb8cf823f036a0c5b3f63c6caa023338dd6c2 specifically)

### CODE REVIEW

**Comment by RavetcoFX** [comment]
Wallpapers on a 4K display seem to be screwing up as well, just from looking at it quickly, you added a GdkRectangle monitor_geometry to libcinnamon-desktop/gnome-bg.c in cinnamon-desktop, I don't know if that has something to do with it.

screenshot from 2016-07-25 01-48-44

**Comment by mtwebster** [comment]
This is to do with scale factors, I haven't tested in hidpi up till now, will fix

**Comment by RavetcoFX** [comment]
Also https://github.com/mtwebster/cinnamon-screensaver/pull/1 in case you didn't see in IRC, when I was trying to make install this branch, it was choking on the webkit-stars example folder because the recursive mode in make was expecting a makefile in the folder, so this PR fixes that

**Comment by leigh123linux** [comment]
There are a few issues here, the unlock dialog doesn't show

here's link to the output

https://paste.fedoraproject.org/397242/89065146/raw/

**Comment by leigh123linux** [comment]
After the changes recommended on irc

```
[leigh@main_pc bin]$ ./cinnamon-screensaver
couldn't grab keyboard
Traceback (most recent call last):
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/overlay.py", line 82, in on_realized
    self.setup_children()
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/overlay.py", line 89, in setup_children
    self.setup_unlock()
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/overlay.py", line 153, in setup_unlock
    self.unlock_dialog = UnlockDialog()
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/unlock.py", line 166, in __init__
    self.update_realname_label()
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/unlock.py", line 299, in update_realname_label
    markup = "<span foreground=\"#3F3F3F\" font_desc=\"Cantarell 14\"><b>%s</b></span>" % (self.real_name)
TypeError: not all arguments converted during string formatting
Emitting ActiveChanged True

(cinnamon-screensaver-main.py:10331): Gtk-WARNING **: Allocating size to GtkOverlay 0x556dc9cf0160 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(cinnamon-screensaver-main.py:10331): Gtk-WARNING **: Allocating size to monitorView+MonitorView 0x556dc9717310 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(cinnamon-screensaver-main.py:10331): Gtk-WARNING **: Allocating size to monitorView+MonitorView 0x556dc9717310 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/overlay.py", line 229, in after_wallpaper_shown_for_unlock
    self.put_on_top(self.unlock_dialog)
  File "/home/leigh/Desktop/cinnamon-screensaver-nextgen/test/share/cinnamon-screensaver/overlay.py", line 301, in put_on_top
    self.overlay.reorder_overlay(widget, -1)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
```

**Comment by leigh123linux** [comment]
With your latest changes I have a unlock dialog and the screensaver part seems to be working ok.

```
[leigh@main_pc bin]$ killall cinnamon-screensaver 
[leigh@main_pc bin]$ killall cinnamon-screensaver 
cinnamon-screensaver: no process found
[leigh@main_pc bin]$ ./cinnamon-screensaver
couldn't grab keyboard
Emitting ActiveChanged True

(cinnamon-screensaver-main.py:21434): Gtk-WARNING **: Allocating size to GtkOverlay 0x56402022e1a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(cinnamon-screensaver-main.py:21434): Gtk-WARNING **: Allocating size to monitorView+MonitorView 0x56401fd5d310 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(cinnamon-screensaver-main.py:21434): Gtk-WARNING **: Allocating size to monitorView+MonitorView 0x56401fd5d310 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Killed
[leigh@main_pc bin]$
```

The above warning are just gtk-3.20 shit and don't seem to affect it's running.

Password unlocking is currently broken, it doesn't except the correct password (says it's incorrect). 
Cinnamon-desktop has your latest commit

https://github.com/mtwebster/cinnamon-desktop/commit/fe5310b26af1ace4620c935575c5944a30223e0d

**Pull request merged**
