### PR TITLE
Avoid ScreensaverService it's not available.

### PR DESCRIPTION
**Pull request by lestcape**

### CODE REVIEW

**Comment by mtwebster** [comment]
What error are you getting that you think this is necessary?  Also, don't use dbus, I've eliminated it as a dependency, we're using GDBus instead.

Currently, if a screensaver is running already (using the bus name we want) the program just quits anyhow.  ScreensaverService is just the python class that implements our service - there's no reason for it to fail (if it is for you, for some reason, let's fix *that*)

**Comment by lestcape** [comment]
lestcape@Vampire:~$ cinnamon-screensaver

** (cinnamon-screensaver-main.py:6057): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-C8uCuifOSG: Conexión rehusada
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 14, in <module>
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 4, in <module>
    gi.require_version('CScreensaver', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace CScreensaver not available

**Comment by lestcape** [comment]
@mtwebster i really, don't know why this occurs then... Anyway if there are a chance to occurs, maybe it's good to avoid that.

That's occurs probably because i have ubuntu 14.04 with Cinnamon 3.0.7...

**Comment by mtwebster** [comment]
CScreensaver is an introspection library provided by libcscreensaver0 package (part of the build for cinnamon-screensaver now) - is that installed?  It's a runtime dependency on cinnamon-screensaver as well.

I just checked and noticed I'm not packaging the /usr/share/gir-1.0 file for some reason (I'll fix that) but the typelib is installed, so it should work.

**Comment by lestcape** [comment]
Edit:
I have not any special/personal reason for try to avoid this, may be only that I'm lazy to update my system to 16.04..

captura de pantalla de 2016-09-03 19 15 02

**Comment by mtwebster** [comment]
Ohhh maybe it's the whole /usr/lib/ and /usr/lib/<arch>/ changes...

The typelib file on xenial is put in /usr/lib/x86_64-linux-gnu/girepository-1.0 for me - I think in trusty they were in simply /usr/lib/girepository-1.0.  I'm not expert on this - I see both folders still exist on my system, I'm just speculating this might be the reason for you.

**Comment by mtwebster** [comment]
I'll test this on my mint 17.3 partition soon and see if i can fix the build to install correctly there.

**Comment by lestcape** [comment]
Ok, but i think your speculation it's the reason... I have not the /usr/lib/x86_64-linux-gnu/girepository-1.0 folder, but instead i have  /usr/lib/girepository-1.0

**Comment by mtwebster** [comment]
I just added https://github.com/linuxmint/cinnamon-screensaver/commit/5772204d41221b79010cef1bc495d25aa3be5498

Hopefully this takes care of things.

**Comment by lestcape** [comment]
I will tell you when i can install it, thanks.

**Comment by JosephMcc** [comment]
Just for info. The new applet settings require at least gtk3.12 and Cinnamon now requires 3.12 to build.

**Comment by lestcape** [comment]
Thanks @JosephMcc this have not reason then...

**Pull request closed without merging**
