### PR TITLE
Change shebang

### PR DESCRIPTION
**Pull request by leigh123linux**

### CODE REVIEW

**Comment by clefebvre** [comment]
I prefer /usr/bin/python3 over env personally, but we need to be consistent... we moved towards env pretty much everywhere, didn't we?

Also, there's no need to add a space after the shebang. I can't remember where/when that was a problem, I know it makes no difference in 99% of the cases, but it was problematic for me once (I remembering tracking it all the way down to dh_python which was even more frustrating.. cause of the sneakiness...).

**Comment by leigh123linux** [comment]
In fedora we aren't allowed to use the env method

https://fedoraproject.org/wiki/Features/SystemPythonExecutablesUseSystemPython

I also agree the space isn't needed, I was copying @mtwebsters shebang used throughout screensaver for consistency .

**Comment by lots0logs** [comment]
It doesnt look like that proposal was actually implemented? Or was the wiki page simply not updated to reflect its completion? IINM, all distros include symlinks in `/usr/bin` that point to the latest versions of python2 and python3 so the rational in that proposal is not really valid today. However, FWIW, I agree with @clefebvre that `/usr/bin/python3` and `/usr/bin/python2` or preferable over  `/usr/bin/env`.

**Comment by leigh123linux** [comment]
@lots0logs I can only find drafts

https://fedoraproject.org/wiki/Script_Interpreters_(draft)

rpmlint treats as an error so requires fixing

**Comment by leigh123linux** [comment]
@clefebvre @lots0logs 
Using env also causes issues

https://bugzilla.redhat.com/show_bug.cgi?id=1284929

**Comment by leigh123linux** [comment]
And another two issues caused by using the env shebang

https://github.com/linuxmint/Cinnamon/issues/4906

https://github.com/linuxmint/Cinnamon/issues/4421

**Comment by clefebvre** [comment]
Look, I totally agree on moving away from env. I really don't see the need for system apps and DEs to follow the user's choice of custom interpreter.

That said, if we do this, we need to decide it as a team, get consensus, and do it everywhere.

**Comment by clefebvre** [comment]
@leigh123linux can you remove the space chars in the shebangs?

**Pull request merged**
