### PR TITLE
Fix python shebang

### PR DESCRIPTION
**Pull request by leigh123linux**

### CODE REVIEW

**Comment by billypeq** [comment]
Hi leigh123linux!

Since you're fixing this part of the code, what about using the structure below? 

#!/usr/bin/env python3

Assuming env is more unlikely to be moved around and to avoid hardcoding Python path. Only a suggestion.

**Comment by leigh123linux** [comment]
The shebang was discussed and is the agreed standard, forcing system python is more robust.

**Comment by billypeq** [comment]
That's OK!Thanks for the reply.

**Comment by clefebvre** [comment]
I need a rebase for this one.

**Comment by leigh123linux** [comment]
@clefebvre  rebased

**Pull request merged**
